[project]
name = "run-movenet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cmake>=4.0.3",
    "numpy==2.1.3",
    "opencv-python>=4.12.0.88",
]
